version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  front:
    build: ./front
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "5173:5173"
      - "6006:6006"